services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: helloworld
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
